install:
    - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
    - cmd: FOR /F "tokens=*" %%F IN ('git describe --tags --abbrev=0') DO SET suffix=%%F

build_script:
    - gradlew.bat shadowJar --info --no-daemon

after_build:
    - iscc.exe /DVersion=%suffix% installers\windows.iss

artifacts:
    - path: installers\*.exe
      name: Windows Installer

deploy:
    provider: GitHub
    auth_token:
        secure: nFrRn+IZKPknIdICYo5wM/+sdiLjLntIBqVyM51t1yKqL4ivfE2Wn2bJsObJqsLZ
    on:
        appveyor_repo_tag: true

