services: [docker]
language: java
os: linux
dist: xenial

before_install:
  - wget https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.1%2B9/OpenJDK15U-jdk_x64_linux_hotspot_15.0.1_9.tar.gz
  - tar xf OpenJDK15U-jdk_x64_linux_hotspot_15.0.1_9.tar.gz
  - export JAVA_HOME=$PWD/jdk-15.0.1+9
  - export PATH=$JAVA_HOME/bin:$PATH

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

script:
  - ./gradlew check

after_success:
  - |
    if [ ! -z "$TRAVIS_TAG" ]; then
      ./gradlew distribzips
    fi

deploy:
  - provider: releases
    token:
      secure: UFyyXv6OGlHHNc10fq2IAYPirAwf0fzjsaF6z/YsUVDXfZjPidiOqyKpRguvhUSg6cRajiqwv2HSd9J04mJsKfuicNWt5IwQZscA9IL25MAgMTGLQKpFY4AMfIA+ZnLy1naFmzshNDKyKUGWw7iu2OQ4+It+QdmGX8EgzmHgwuI7Db9YVJnge1D2LU7q5XZTmEo7Xt/w9L9qNTB2r0wpK67OxkbYbtJLOyWtnGc87GlprKsuwjiCW3u4cKgf+82y+mjl/Ce+HFJQrjk5Yfy2h89T9GdtqTZvH+ktKg33k/jyLcV5tMuaKmOK9ok5c80r0gVp+kqe9TE6aICBj2KEiRiHzTQl14MQ1uwBwEyZKqIgkrZ1nKDukbYIPUSR0FMVWZaxPFLZuRjp16rKJ3Ae2vuzMFPbqoFA/Ed0xnYDoCto3/a0uaAMWVBjxwkXfuqpeZfeSt9XtuK9CfqrSl+5MoYyLHlYqz2FSBdsb/kiM+KshUGTjVzJI0HHa0of0fO/w7gfFbg+ekq2bcPBkuigywF5Pecshhn/avuJwjwGc+uNrr4WJVxkdpJNUQxD7Ve/UXni9NOiHFjE/2k8INAomA5wnzgkEVLxGBvyyfXdB88EMR5QIEVe+v6RFIPEFeWGxpx/+9IQ9n5NcTLP5SIq2Dr3BCsObpNLEVSnlybsNhY=
    cleanup: false
    file_glob: true
    file:
      - "build/image/*.zip"
    on:
      tags: true

#  - provider: gcs
#    access_key_id: GOOG1E5JH6W2HZ3MNAWHD26RUULDCZQLS7ZRPUCLWO6DQBKJ2DB4G2ZLQIGTA
#    secret_access_key:
#      secure: qt1LiXpdFLopEDFj5ptWG05scr0bvXetKIiVRHwrA2t5ah5g6mwy59fsa75rU20HseqQgljW0p9pvzrms5beDWrc9bSXX5dMN9TSCpBV9o6LjtPgocctVXfLyv1OI7j3F7xbnI9VrAjoPRaTV/bZkFlv3SWpKaz9eQwrqUBypL/B8DumDRl82O9+dklAFjD+LEKPNrEhU7TkUhPsonUFiQKix8gK/ArMGxIJey+3hGFBWjWTv8FJzfz++EAEV17tqTSCeLgrflj4jvZPnHWlfQXMljzwVbqRHTaFod+PZOWrfvt2PQnbsEhSwzz24NpH9X2ShWHRkC4LWqCDsE0yrczcgdAlAEvTPi7s2aQfpH/fcDphtCX6S+OVymqfduQREEGOmlm5KfzFgRBsdwaZovfVBD7CKR01CYH2XgD1NSCuR7qks8TwTUyypbwKleR5wdZbU+v4PfZn/BGYpzPBMpCHINz/HmlxRoQnn9GftOAGHaMs/6iahOpl69FVShn1IcwVEjVZ7m2KH29Y/1jUhrYe/4XVObQEAHMDOFL/jCdswBADjFcIuj87FodrFmigJ1UB/qX7wawI2JfkwtimVhQktX9M5/kr+sp4yHQmHeBSaDqgb+WjSn9LVT9qOW8312Vz93WGaTl3KUncoTXz7R0uHXCwYiLYn4xgKQBGfog=
#    bucket: scorekeeper-artifacts
#    skip_cleanup: true
#    local-dir: "build/final"
